Added inkscape modules
Neon22/inkscape_extension_template pull request #5
Opened 2018-10-05 08:14 UTC by Zedonboy

Added inkscape modules so users can easily work with the files from their IDE

2018-10-05 10:42 UTC, Neon22 commented
putting all the extensions code in here seems like doing it backwards ??

The idea was you can use this as a template when making new inx and py files for an inkscape extension.
It has not been updated for the upcoming 1.0 release.
See gitlab extensions sub repo for up to date code of the main extensions code.
https://gitlab.com/inkscape/extensions

2020-02-27 15:30 UTC, oxr463 requested changes
These should not go in this repository.

It would be better to document installing the extensions locally and then requiring as needed.

2020-02-27 20:51 UTC, Neon22 commented on template.py
> +sys.path.insert(0, "./inkscape_pymodules")
I don't agree with putting msoft visual studio cruft into anything.
please remove

2020-02-27 20:55 UTC, Neon22 commented
the added codes don't belong here. If they did then every single extension would bloat the system with hundreds of duplicate folders with the same code in it.
So rejecting

2020-02-27 20:55 UTC, closed without merging